const ApiConstants = {

    UPDATE_LOADING_STATE: "UPDATE_LOADING_STATE",

    API_SIGNUP_LOAD: "API_SIGNUP_LOAD",
    API_SIGNUP_SUCCESS: "API_SIGNUP_SUCCESS",
    
    API_LOGIN_LOAD: "API_LOGIN_LOAD",
    API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
    
    API_FORGOT_PASSWORD_LOAD: "API_FORGOT_PASSWORD_LOAD",
    API_FORGOT_PASSWORD_SUCCESS: "API_FORGOT_PASSWORD_SUCCESS",

    ACCOUNT_DELETE_LOAD: "ACCOUNT_DELETE_LOAD",
    ACCOUNT_DELETE_SUCCESS: "ACCOUNT_DELETE_SUCCESS",

    USER_DETAILS_LOAD: "USER_DETAILS_LOAD",
    USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
    
    EDIT_PROFILE_LOAD: "EDIT_PROFILE_LOAD",
    EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
    
    CHANGE_PASSWORD_LOAD: "CHANGE_PASSWORD_LOAD",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",

    USER_QUIZ_LOAD: "USER_QUIZ_LOAD",
    USER_QUIZ_SUCCESS: "USER_QUIZ_SUCCESS",

    QUIZ_ANSWER_LOAD: "QUIZ_ANSWER_LOAD",
    QUIZ_ANSWER_SUCCESS: "QUIZ_ANSWER_SUCCESS",

    NOTIFICATION_SOUND_LOAD: "NOTIFICATION_SOUND_LOAD",
    NOTIFICATION_SOUND_SUCCESS: "NOTIFICATION_SOUND_SUCCESS",
    
    RESET_AUTH_DATA: "RESET_AUTH_DATA",
  }
  
  export default ApiConstants;