const ApiConstants = {

    UPDATE_LODING_STATE: "UPDATE_LODING_STATE",

    API_SIGNUP_LOAD: "API_SIGNUP_LOAD",
    API_SIGNUP_SUCCESS: "API_SIGNUP_SUCCESS",
    
    API_LOGIN_LOAD: "API_LOGIN_LOAD",
    API_LOGIN_SUCCESS: "API_LOGIN_SUCCESS",
    
    API_FORGOT_PASSWORD_LOAD: "API_FORGOT_PASSWORD_LOAD",
    API_FORGOT_PASSWORD_SUCCESS: "API_FORGOT_PASSWORD_SUCCESS",
    
    RESET_AUTH_DATA: "RESET_AUTH_DATA",
  }
  
  export default ApiConstants;